import * as vscode from 'vscode';
import { getPreferredWorkspaceFolder } from '../utils/workspace';

import * as fs from 'fs';
import * as path from 'path';

/**
 * AI Context Generator (Harness Engineering - Pillar 1: Context Engineering)
 * Provides deterministic rules and project state for AI Coding Assistants (Cursor, Copilot, etc.)
 * to prevent hallucination of ArkTS APIs.
 */
export class AiContextGenerator {
  
  public static async generateContext(): Promise<void> {
    const workspace = getPreferredWorkspaceFolder();
    if (!workspace) {
      vscode.window.showErrorMessage('No HarmonyOS workspace found for AI Context Generation.');
      return;
    }

    try {
      const contextContent = await this.buildContextContent(workspace.uri);
      
      const cursorRulesPath = path.join(workspace.uri.fsPath, '.cursorrules');
      fs.writeFileSync(cursorRulesPath, contextContent, 'utf8');

      vscode.window.showInformationMessage(`Successfully generated .cursorrules to enforce AI Harness constraints.`);
    } catch (err: any) {
      vscode.window.showErrorMessage(`Failed to generate AI context: ${err.message}`);
    }
  }

  private static async buildContextContent(workspaceUri: vscode.Uri): Promise<string> {
    let apiLevel = 'Unknown';
    try {
      const buildProfilePath = path.join(workspaceUri.fsPath, 'build-profile.json5');
      if (fs.existsSync(buildProfilePath)) {
        const bp = JSON.parse(fs.readFileSync(buildProfilePath, 'utf8'));
        apiLevel = bp.app?.products?.[0]?.compileSdkVersion || apiLevel;
      }
    } catch (e) {
      // Ignore parse errors
    }

    let dependencies: Record<string, string> = {};
    try {
      const ohPackagePath = path.join(workspaceUri.fsPath, 'oh-package.json5');
      if (fs.existsSync(ohPackagePath)) {
         const ohPkg = JSON.parse(fs.readFileSync(ohPackagePath, 'utf8'));
         dependencies = ohPkg.dependencies || {};
      }
    } catch (e) {
      // Ignore
    }

    const libs = Object.entries(dependencies).map(([name, ver]) => `- ${name}: ${ver}`).join('\n');

    return `
# HarmonyOS ArkTS AI Harness Context

## Mechanical Constraints
You are an AI Coding Agent writing code for a HarmonyOS application.
You MUST strictly adhere to the following architectural constraints:

### 1. Project Reality
- **Compile SDK API Level:** ${apiLevel}
- **Language:** ArkTS / Cangjie
- **Decorators:** Prefer V2 decorators (\`@ComponentV2\`, \`@Local\`, \`@Param\`, \`@Event\`) if the project actively uses them. DO NOT mix V1 (\`@State\`) and V2 decorators in the same struct.

### 2. Architectural Boundaries (STRICT)
- **Component Purity:** Files inside \`components/\` directories MUST NOT use the \`@Entry\` decorator. They are reusable UI pieces.
- **Page Isolation:** Files inside \`pages/\` directories MUST NOT import other pages. Navigation must happen via \`@ohos.router\` or Navigation component.
- **Routing Decoupling:** Files inside \`components/\` directories SHOULD NOT import \`@ohos.router\`. Pass callbacks from pages instead.

### 3. Resource Management
- Always use \`$r('app.xx.yy')\` for resources.
- Ensure all newly referenced strings and media are properly defined in \`resources/base/element/string.json\`.
- Do not hallucinate resources.

### 4. Known Dependencies in Workspace
${libs ? libs : '- No third-party dependencies detected.'}

> Note: This context is mechanically generated by the HarmonyOS Dev Tools extension to enforce Harness Engineering principles.
`.trim();
  }
}
