#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2023 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------
#  Hvigor startup script, version 1.0.0
# 
#  Required ENV vars:
#  ------------------
#    NODE_HOME - location of a Node home dir
#    or 
#    Add /usr/local/nodejs/bin to the PATH environment variable
# ----------------------------------------------------------------------------

HVIGOR_APP_HOME=$(dirname $(readlink -f $0))
HVIGOR_WRAPPER_SCRIPT=${HVIGOR_APP_HOME}/hvigor/hvigor-wrapper.js
warn() {
	echo ""
	echo -e "\033[1;33m`date '+[%Y-%m-%d %H:%M:%S]'`$@\033[0m"
}

error() {
	echo ""
	echo -e "\033[1;31m`date '+[%Y-%m-%d %H:%M:%S]'`$@\033[0m"
}

fail() {
	error "$@"
	exit 1
}

# Determine node to start hvigor wrapper script
if [ -n "${NODE_HOME}" ];then
   EXECUTABLE_NODE="${NODE_HOME}/bin/node"
   if [ ! -x "$EXECUTABLE_NODE" ];then
       fail "ERROR: NODE_HOME is set to an invalid directory,check $NODE_HOME\n\nPlease set NODE_HOME in your environment to the location where your nodejs installed"
   fi
else
   EXECUTABLE_NODE="node"
   which ${EXECUTABLE_NODE} > /dev/null 2>&1 || fail "ERROR: NODE_HOME is not set and not 'node' command found in your path"
fi

# Check hvigor wrapper script
if [ ! -r "$HVIGOR_WRAPPER_SCRIPT" ];then
	fail "ERROR: Couldn't find hvigor/hvigor-wrapper.js in ${HVIGOR_APP_HOME}"
fi

# Use project-level npm config for hvigor dependency installation.
PROJECT_NPMRC="${HVIGOR_APP_HOME}/.npmrc"
if [ -f "$PROJECT_NPMRC" ]; then
	export NPM_CONFIG_USERCONFIG="$PROJECT_NPMRC"
fi

# Make hvigor cached dependencies resolvable by hvigorfile.ts imports.
PROJECT_HASH=$("${EXECUTABLE_NODE}" -e "const crypto=require('crypto');console.log(crypto.createHash('md5').update(process.argv[1],'utf8').digest('hex'))" "${HVIGOR_APP_HOME}")
HVIGOR_NODE_MODULES="${HOME}/.hvigor/project_caches/${PROJECT_HASH}/workspace/node_modules"
if [ -d "$HVIGOR_NODE_MODULES" ]; then
	if [ -n "$NODE_PATH" ]; then
		export NODE_PATH="${HVIGOR_NODE_MODULES}:${NODE_PATH}"
	else
		export NODE_PATH="${HVIGOR_NODE_MODULES}"
	fi

	# Expose hvigor plugin to project-root resolution for hvigorfile.ts.
	LOCAL_OHOS_NODE_MODULES="${HVIGOR_APP_HOME}/node_modules/@ohos"
	mkdir -p "${LOCAL_OHOS_NODE_MODULES}" 2>/dev/null
	ln -snf "${HVIGOR_NODE_MODULES}/@ohos/hvigor-ohos-plugin" "${LOCAL_OHOS_NODE_MODULES}/hvigor-ohos-plugin" 2>/dev/null
fi

# start hvigor-wrapper script
exec "${EXECUTABLE_NODE}" \
	"${HVIGOR_WRAPPER_SCRIPT}" "$@"
